import type { NavItem, Category } from "@/lib/types";

export interface SubcategoryDef { id: Category; name: string; }
export interface CategoryDef { id: Category; name: string; type: "income" | "expense" | "transfer"; subcategories: SubcategoryDef[]; }

export const CATEGORY_HIERARCHY: CategoryDef[] = [
  // ── Income ────────────────────────────────────────────────────────────────
  { id: "salary", name: "Salary & Wages", type: "income", subcategories: [
    { id: "salary_regular", name: "Regular paycheck" },
    { id: "salary_overtime", name: "Overtime pay" },
    { id: "salary_bonus", name: "Bonus" },
    { id: "salary_commission", name: "Commission" },
    { id: "salary_tips", name: "Tips" },
  ]},
  { id: "freelance", name: "Freelance & Gig", type: "income", subcategories: [
    { id: "freelance_contract", name: "Contract work" },
    { id: "freelance_consulting", name: "Consulting" },
    { id: "freelance_gig_platform", name: "Gig platform" },
    { id: "freelance_royalties", name: "Royalties" },
    { id: "freelance_speaking", name: "Speaking / appearances" },
  ]},
  { id: "business_income", name: "Business Income", type: "income", subcategories: [
    { id: "business_income_product_sales", name: "Product sales" },
    { id: "business_income_service_revenue", name: "Service revenue" },
    { id: "business_income_affiliate", name: "Affiliate income" },
    { id: "business_income_licensing", name: "Licensing fees" },
    { id: "business_income_rental", name: "Rental income" },
  ]},
  { id: "investments", name: "Investment Income", type: "income", subcategories: [
    { id: "investments_dividends", name: "Dividends" },
    { id: "investments_interest", name: "Interest earned" },
    { id: "investments_capital_gains", name: "Capital gains" },
    { id: "investments_crypto_gains", name: "Crypto gains" },
    { id: "investments_stock_options", name: "Stock options" },
  ]},
  { id: "gov_benefits", name: "Government & Benefits", type: "income", subcategories: [
    { id: "gov_social_security", name: "Social Security" },
    { id: "gov_unemployment", name: "Unemployment" },
    { id: "gov_disability", name: "Disability (SSDI/SDI)" },
    { id: "gov_veterans", name: "Veterans benefits" },
    { id: "gov_child_support", name: "Child support / alimony" },
  ]},
  { id: "refunds", name: "Refunds & Reimbursements", type: "income", subcategories: [
    { id: "refunds_tax", name: "Tax refund" },
    { id: "refunds_purchase", name: "Purchase refund" },
    { id: "refunds_insurance", name: "Insurance reimbursement" },
    { id: "refunds_expense", name: "Expense reimbursement" },
    { id: "refunds_warranty", name: "Warranty claim" },
  ]},
  { id: "gifts", name: "Gifts & Windfalls", type: "income", subcategories: [
    { id: "gifts_cash", name: "Cash gift" },
    { id: "gifts_inheritance", name: "Inheritance" },
    { id: "gifts_prize", name: "Prize / lottery" },
    { id: "gifts_crowdfunding", name: "Crowdfunding received" },
    { id: "gifts_gift_card", name: "Monetary gift card" },
  ]},
  { id: "other_income", name: "Other Income", type: "income", subcategories: [
    { id: "other_income_cashback", name: "Cashback reward" },
    { id: "other_income_survey", name: "Survey / research payout" },
    { id: "other_income_selling", name: "Selling personal items" },
    { id: "other_income_misc", name: "Miscellaneous income" },
  ]},
  // ── Expense ───────────────────────────────────────────────────────────────
  { id: "housing", name: "Housing", type: "expense", subcategories: [
    { id: "housing_rent_mortgage", name: "Rent / mortgage" },
    { id: "housing_hoa", name: "HOA fees" },
    { id: "housing_property_tax", name: "Property tax" },
    { id: "housing_insurance", name: "Renters / homeowners insurance" },
    { id: "housing_repairs", name: "Repairs & maintenance" },
    { id: "housing_cleaning", name: "Cleaning services" },
    { id: "housing_pest_control", name: "Pest control" },
    { id: "housing_security", name: "Home security" },
  ]},
  { id: "transportation", name: "Transportation", type: "expense", subcategories: [
    { id: "transport_gas", name: "Gas / fuel" },
    { id: "transport_car_payment", name: "Car payment" },
    { id: "transport_auto_insurance", name: "Auto insurance" },
    { id: "transport_parking_tolls", name: "Parking & tolls" },
    { id: "transport_maintenance", name: "Car maintenance & repairs" },
    { id: "transport_public_transit", name: "Public transit" },
    { id: "transport_rideshare", name: "Rideshare (Uber / Lyft)" },
    { id: "transport_bike_scooter", name: "Bike / scooter rental" },
    { id: "transport_registration", name: "Registration & DMV fees" },
  ]},
  { id: "food_dining", name: "Food & Dining", type: "expense", subcategories: [
    { id: "food_groceries", name: "Groceries" },
    { id: "food_restaurants", name: "Restaurants & dining out" },
    { id: "food_fast_food", name: "Fast food" },
    { id: "food_coffee", name: "Coffee shops" },
    { id: "food_delivery", name: "Food delivery" },
    { id: "food_alcohol", name: "Alcohol & bars" },
    { id: "food_meal_kits", name: "Meal prep & kits" },
  ]},
  { id: "utilities", name: "Utilities & Bills", type: "expense", subcategories: [
    { id: "utilities_electricity", name: "Electricity" },
    { id: "utilities_water", name: "Water & sewer" },
    { id: "utilities_gas", name: "Gas / heating" },
    { id: "utilities_internet", name: "Internet" },
    { id: "utilities_mobile", name: "Mobile phone" },
    { id: "utilities_landline", name: "Landline" },
    { id: "utilities_trash", name: "Trash & recycling" },
  ]},
  { id: "healthcare", name: "Healthcare & Wellness", type: "expense", subcategories: [
    { id: "health_doctor", name: "Doctor & physician" },
    { id: "health_dentist", name: "Dentist" },
    { id: "health_vision", name: "Vision / eye care" },
    { id: "health_prescriptions", name: "Prescription medications" },
    { id: "health_equipment", name: "Medical equipment" },
    { id: "health_insurance", name: "Health insurance premium" },
    { id: "health_mental", name: "Mental health / therapy" },
    { id: "health_gym", name: "Gym & fitness" },
    { id: "health_supplements", name: "Supplements & vitamins" },
  ]},
  { id: "personal_care", name: "Personal Care", type: "expense", subcategories: [
    { id: "personal_haircut", name: "Haircut & salon" },
    { id: "personal_spa", name: "Spa & massage" },
    { id: "personal_skincare", name: "Skincare & beauty" },
    { id: "personal_grooming", name: "Grooming products" },
    { id: "personal_clothing", name: "Clothing & apparel" },
    { id: "personal_laundry", name: "Laundry & dry cleaning" },
  ]},
  { id: "entertainment", name: "Entertainment", type: "expense", subcategories: [
    { id: "entertainment_streaming", name: "Streaming services" },
    { id: "entertainment_movies_concerts", name: "Movies & concerts" },
    { id: "entertainment_video_games", name: "Video games" },
    { id: "entertainment_sports_rec", name: "Sports & recreation" },
    { id: "entertainment_books", name: "Books & magazines" },
    { id: "entertainment_hobbies", name: "Hobbies & crafts" },
    { id: "entertainment_nightlife", name: "Events & nightlife" },
    { id: "entertainment_attractions", name: "Amusement & attractions" },
  ]},
  { id: "shopping", name: "Shopping", type: "expense", subcategories: [
    { id: "shopping_electronics", name: "Electronics & gadgets" },
    { id: "shopping_clothing", name: "Clothing & fashion" },
    { id: "shopping_home_goods", name: "Home goods & furniture" },
    { id: "shopping_sports_equipment", name: "Sports equipment" },
    { id: "shopping_toys_kids", name: "Toys & kids items" },
    { id: "shopping_pet_supplies", name: "Pet supplies" },
    { id: "shopping_online_marketplace", name: "Online marketplace" },
    { id: "shopping_gifts_purchased", name: "Gifts purchased" },
  ]},
  { id: "education", name: "Education", type: "expense", subcategories: [
    { id: "education_tuition", name: "Tuition & school fees" },
    { id: "education_student_loan", name: "Student loan payment" },
    { id: "education_books_supplies", name: "Books & supplies" },
    { id: "education_online_courses", name: "Online courses" },
    { id: "education_tutoring", name: "Tutoring" },
    { id: "education_childcare", name: "Childcare & daycare" },
    { id: "education_school_activities", name: "School activities" },
  ]},
  { id: "family_childcare", name: "Family & Childcare", type: "expense", subcategories: [
    { id: "family_daycare", name: "Childcare / daycare" },
    { id: "family_baby_supplies", name: "Baby supplies" },
    { id: "family_kids_activities", name: "Kids activities" },
    { id: "family_child_support_paid", name: "Child support paid" },
    { id: "family_alimony_paid", name: "Alimony paid" },
    { id: "family_elder_care", name: "Elder care" },
  ]},
  { id: "pets", name: "Pets", type: "expense", subcategories: [
    { id: "pets_food", name: "Pet food" },
    { id: "pets_vet", name: "Vet & medical" },
    { id: "pets_grooming", name: "Grooming" },
    { id: "pets_insurance", name: "Pet insurance" },
    { id: "pets_boarding", name: "Boarding & kennel" },
    { id: "pets_supplies", name: "Pet supplies & accessories" },
  ]},
  { id: "subscriptions", name: "Subscriptions & Memberships", type: "expense", subcategories: [
    { id: "subscriptions_software", name: "Software (SaaS)" },
    { id: "subscriptions_streaming_video", name: "Streaming (video)" },
    { id: "subscriptions_streaming_music", name: "Streaming (music)" },
    { id: "subscriptions_news_media", name: "News & media" },
    { id: "subscriptions_gym_club", name: "Club or gym membership" },
    { id: "subscriptions_professional", name: "Professional membership" },
    { id: "subscriptions_apps", name: "App subscriptions" },
    { id: "subscriptions_box", name: "Box subscriptions" },
  ]},
  { id: "travel", name: "Travel", type: "expense", subcategories: [
    { id: "travel_flights", name: "Flights" },
    { id: "travel_hotels", name: "Hotels & lodging" },
    { id: "travel_vacation_rental", name: "Vacation rentals (Airbnb)" },
    { id: "travel_car_rental", name: "Car rental" },
    { id: "travel_insurance", name: "Travel insurance" },
    { id: "travel_activities", name: "Activities & excursions" },
    { id: "travel_cruises", name: "Cruises" },
    { id: "travel_docs", name: "Visa & travel docs" },
  ]},
  { id: "insurance", name: "Insurance", type: "expense", subcategories: [
    { id: "insurance_life", name: "Life insurance" },
    { id: "insurance_disability", name: "Disability insurance" },
    { id: "insurance_umbrella", name: "Umbrella insurance" },
    { id: "insurance_liability", name: "Liability insurance" },
  ]},
  { id: "financial_fees", name: "Financial & Banking Fees", type: "expense", subcategories: [
    { id: "fees_bank", name: "Bank fees" },
    { id: "fees_atm", name: "ATM fees" },
    { id: "fees_overdraft", name: "Overdraft fee" },
    { id: "fees_wire_transfer", name: "Wire transfer fee" },
    { id: "fees_investment", name: "Investment fees" },
    { id: "fees_tax_prep", name: "Tax preparation" },
    { id: "fees_accounting", name: "Accounting services" },
  ]},
  { id: "taxes", name: "Taxes", type: "expense", subcategories: [
    { id: "taxes_federal", name: "Federal income tax" },
    { id: "taxes_state", name: "State income tax" },
    { id: "taxes_self_employment", name: "Self-employment tax" },
    { id: "taxes_property", name: "Property tax" },
    { id: "taxes_sales", name: "Sales tax (tracked)" },
    { id: "taxes_quarterly", name: "Estimated quarterly tax" },
  ]},
  { id: "charity", name: "Charity & Giving", type: "expense", subcategories: [
    { id: "charity_nonprofit", name: "Nonprofit donations" },
    { id: "charity_religious", name: "Religious giving / tithe" },
    { id: "charity_fundraising", name: "Fundraising contributions" },
    { id: "charity_sponsorships", name: "Sponsorships" },
  ]},
  { id: "debt_payments", name: "Debt Payments", type: "expense", subcategories: [
    { id: "debt_credit_card", name: "Credit card payment" },
    { id: "debt_personal_loan", name: "Personal loan" },
    { id: "debt_student_loan", name: "Student loan" },
    { id: "debt_medical", name: "Medical debt" },
    { id: "debt_bnpl", name: "Buy Now Pay Later (BNPL)" },
    { id: "debt_collections", name: "Collections / past due" },
  ]},
  { id: "business_expenses", name: "Business Expenses", type: "expense", subcategories: [
    { id: "biz_office_supplies", name: "Office supplies" },
    { id: "biz_software_tools", name: "Software & tools" },
    { id: "biz_marketing", name: "Marketing & advertising" },
    { id: "biz_professional_services", name: "Professional services" },
    { id: "biz_travel", name: "Business travel" },
    { id: "biz_client_meals", name: "Client meals & entertainment" },
    { id: "biz_equipment", name: "Equipment purchase" },
  ]},
  { id: "other_expenses", name: "Other Expenses", type: "expense", subcategories: [
    { id: "other_exp_legal", name: "Legal fees" },
    { id: "other_exp_fines", name: "Fines & penalties" },
    { id: "other_exp_cash", name: "Cash withdrawal" },
    { id: "other_exp_misc", name: "Miscellaneous" },
  ]},
  // ── Transfer ──────────────────────────────────────────────────────────────
  { id: "savings_investments", name: "Savings & Investments", type: "transfer", subcategories: [
    { id: "savings_emergency_fund", name: "Emergency fund" },
    { id: "savings_hysa", name: "High-yield savings" },
    { id: "savings_brokerage", name: "Brokerage account" },
    { id: "savings_crypto", name: "Cryptocurrency purchase" },
    { id: "savings_retirement", name: "Retirement contribution (IRA/401k)" },
    { id: "savings_cd", name: "CD / money market" },
  ]},
  { id: "account_transfers", name: "Account Transfers", type: "transfer", subcategories: [
    { id: "transfer_checking_savings", name: "Checking to savings" },
    { id: "transfer_own_accounts", name: "Between own accounts" },
    { id: "transfer_joint", name: "Joint account transfer" },
    { id: "transfer_escrow", name: "Escrow / trust deposit" },
  ]},
  { id: "pay_person", name: "Payments to People", type: "transfer", subcategories: [
    { id: "p2p_venmo_paypal_zelle", name: "Venmo / PayPal / Zelle" },
    { id: "p2p_rent_roommate", name: "Rent to roommate" },
    { id: "p2p_split_bill", name: "Split bill" },
    { id: "p2p_loan_friend", name: "Loan to friend" },
    { id: "p2p_repayment", name: "Repayment received" },
  ]},
];

export const NAV_ITEMS: NavItem[] = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "My Banks", href: "/my-banks", icon: "Landmark" },
  { label: "Portfolio", href: "/portfolio", icon: "BarChart2" },
  { label: "Algo Strategies", href: "/algo-strategies", icon: "Bot" },
  { label: "Budgets", href: "/budgets", icon: "Wallet" },
  { label: "Goals", href: "/goals", icon: "Target" },
  { label: "Advisor Academy", href: "/intelligence/career", icon: "Brain" },
  { label: "Transactions", href: "/transactions", icon: "ArrowLeftRight" },
  { label: "Income", href: "/income", icon: "TrendingUp" },
  { label: "Expense", href: "/expense", icon: "TrendingDown" },
  { label: "Transfer Funds", href: "/transfer", icon: "SendHorizontal" },
  { label: "Assistant", href: "/assistant", icon: "MessageCircle" },
  { label: "Resource Vault", href: "/resources", icon: "BookMarked" },
  { label: "Notifications", href: "/notifications", icon: "Bell" },
  { label: "Pricing", href: "/pricing", icon: "CreditCard" },
  { label: "Settings", href: "/settings", icon: "Settings" },
  { label: "Admin", href: "/admin", icon: "Shield" },
];

export const CATEGORY_LABELS: Record<Category, string> = {
  // ─── Legacy ────────────────────────────────────────────────────────────────
  investment: "Investment", refund: "Refund", food: "Food & Dining",
  transfer: "Transfer", other: "Other",
  // ─── Income — top level ────────────────────────────────────────────────────
  salary: "Salary & Wages", freelance: "Freelance & Gig",
  business_income: "Business Income", investments: "Investment Income",
  gov_benefits: "Government & Benefits", refunds: "Refunds & Reimbursements",
  gifts: "Gifts & Windfalls", other_income: "Other Income",
  // ─── Income — subcategories ────────────────────────────────────────────────
  salary_regular: "Regular Paycheck", salary_overtime: "Overtime Pay",
  salary_bonus: "Bonus", salary_commission: "Commission", salary_tips: "Tips",
  freelance_contract: "Contract Work", freelance_consulting: "Consulting",
  freelance_gig_platform: "Gig Platform", freelance_royalties: "Royalties",
  freelance_speaking: "Speaking / Appearances",
  business_income_product_sales: "Product Sales",
  business_income_service_revenue: "Service Revenue",
  business_income_affiliate: "Affiliate Income",
  business_income_licensing: "Licensing Fees",
  business_income_rental: "Rental Income",
  investments_dividends: "Dividends", investments_interest: "Interest Earned",
  investments_capital_gains: "Capital Gains", investments_crypto_gains: "Crypto Gains",
  investments_stock_options: "Stock Options",
  gov_social_security: "Social Security", gov_unemployment: "Unemployment",
  gov_disability: "Disability (SSDI/SDI)", gov_veterans: "Veterans Benefits",
  gov_child_support: "Child Support / Alimony",
  refunds_tax: "Tax Refund", refunds_purchase: "Purchase Refund",
  refunds_insurance: "Insurance Reimbursement", refunds_expense: "Expense Reimbursement",
  refunds_warranty: "Warranty Claim",
  gifts_cash: "Cash Gift", gifts_inheritance: "Inheritance",
  gifts_prize: "Prize / Lottery", gifts_crowdfunding: "Crowdfunding Received",
  gifts_gift_card: "Monetary Gift Card",
  other_income_cashback: "Cashback Reward", other_income_survey: "Survey / Research Payout",
  other_income_selling: "Selling Personal Items", other_income_misc: "Miscellaneous Income",
  // ─── Expense — top level ───────────────────────────────────────────────────
  housing: "Housing", transportation: "Transportation", food_dining: "Food & Dining",
  utilities: "Utilities & Bills", healthcare: "Healthcare & Wellness",
  personal_care: "Personal Care", entertainment: "Entertainment", shopping: "Shopping",
  education: "Education", family_childcare: "Family & Childcare", pets: "Pets",
  subscriptions: "Subscriptions & Memberships", travel: "Travel",
  insurance: "Insurance", financial_fees: "Financial & Banking Fees", taxes: "Taxes",
  charity: "Charity & Giving", debt_payments: "Debt Payments",
  business_expenses: "Business Expenses", other_expenses: "Other Expenses",
  // ─── Expense — subcategories ───────────────────────────────────────────────
  housing_rent_mortgage: "Rent / Mortgage", housing_hoa: "HOA Fees",
  housing_property_tax: "Property Tax", housing_insurance: "Renters / Homeowners Insurance",
  housing_repairs: "Repairs & Maintenance", housing_cleaning: "Cleaning Services",
  housing_pest_control: "Pest Control", housing_security: "Home Security",
  transport_gas: "Gas / Fuel", transport_car_payment: "Car Payment",
  transport_auto_insurance: "Auto Insurance", transport_parking_tolls: "Parking & Tolls",
  transport_maintenance: "Car Maintenance & Repairs", transport_public_transit: "Public Transit",
  transport_rideshare: "Rideshare (Uber / Lyft)", transport_bike_scooter: "Bike / Scooter Rental",
  transport_registration: "Registration & DMV Fees",
  food_groceries: "Groceries", food_restaurants: "Restaurants & Dining Out",
  food_fast_food: "Fast Food", food_coffee: "Coffee Shops",
  food_delivery: "Food Delivery", food_alcohol: "Alcohol & Bars",
  food_meal_kits: "Meal Prep & Kits",
  utilities_electricity: "Electricity", utilities_water: "Water & Sewer",
  utilities_gas: "Gas / Heating", utilities_internet: "Internet",
  utilities_mobile: "Mobile Phone", utilities_landline: "Landline",
  utilities_trash: "Trash & Recycling",
  health_doctor: "Doctor & Physician", health_dentist: "Dentist",
  health_vision: "Vision / Eye Care", health_prescriptions: "Prescription Medications",
  health_equipment: "Medical Equipment", health_insurance: "Health Insurance Premium",
  health_mental: "Mental Health / Therapy", health_gym: "Gym & Fitness",
  health_supplements: "Supplements & Vitamins",
  personal_haircut: "Haircut & Salon", personal_spa: "Spa & Massage",
  personal_skincare: "Skincare & Beauty", personal_grooming: "Grooming Products",
  personal_clothing: "Clothing & Apparel", personal_laundry: "Laundry & Dry Cleaning",
  entertainment_streaming: "Streaming Services",
  entertainment_movies_concerts: "Movies & Concerts",
  entertainment_video_games: "Video Games", entertainment_sports_rec: "Sports & Recreation",
  entertainment_books: "Books & Magazines", entertainment_hobbies: "Hobbies & Crafts",
  entertainment_nightlife: "Events & Nightlife",
  entertainment_attractions: "Amusement & Attractions",
  shopping_electronics: "Electronics & Gadgets", shopping_clothing: "Clothing & Fashion",
  shopping_home_goods: "Home Goods & Furniture", shopping_sports_equipment: "Sports Equipment",
  shopping_toys_kids: "Toys & Kids Items", shopping_pet_supplies: "Pet Supplies",
  shopping_online_marketplace: "Online Marketplace",
  shopping_gifts_purchased: "Gifts Purchased",
  education_tuition: "Tuition & School Fees", education_student_loan: "Student Loan Payment",
  education_books_supplies: "Books & Supplies", education_online_courses: "Online Courses",
  education_tutoring: "Tutoring", education_childcare: "Childcare & Daycare",
  education_school_activities: "School Activities",
  family_daycare: "Childcare / Daycare", family_baby_supplies: "Baby Supplies",
  family_kids_activities: "Kids Activities", family_child_support_paid: "Child Support Paid",
  family_alimony_paid: "Alimony Paid", family_elder_care: "Elder Care",
  pets_food: "Pet Food", pets_vet: "Vet & Medical", pets_grooming: "Grooming",
  pets_insurance: "Pet Insurance", pets_boarding: "Boarding & Kennel",
  pets_supplies: "Pet Supplies & Accessories",
  subscriptions_software: "Software (SaaS)", subscriptions_streaming_video: "Streaming (Video)",
  subscriptions_streaming_music: "Streaming (Music)", subscriptions_news_media: "News & Media",
  subscriptions_gym_club: "Club or Gym Membership",
  subscriptions_professional: "Professional Membership",
  subscriptions_apps: "App Subscriptions", subscriptions_box: "Box Subscriptions",
  travel_flights: "Flights", travel_hotels: "Hotels & Lodging",
  travel_vacation_rental: "Vacation Rentals (Airbnb)", travel_car_rental: "Car Rental",
  travel_insurance: "Travel Insurance", travel_activities: "Activities & Excursions",
  travel_cruises: "Cruises", travel_docs: "Visa & Travel Docs",
  insurance_life: "Life Insurance", insurance_disability: "Disability Insurance",
  insurance_umbrella: "Umbrella Insurance", insurance_liability: "Liability Insurance",
  fees_bank: "Bank Fees", fees_atm: "ATM Fees", fees_overdraft: "Overdraft Fee",
  fees_wire_transfer: "Wire Transfer Fee", fees_investment: "Investment Fees",
  fees_tax_prep: "Tax Preparation", fees_accounting: "Accounting Services",
  taxes_federal: "Federal Income Tax", taxes_state: "State Income Tax",
  taxes_self_employment: "Self-Employment Tax", taxes_property: "Property Tax",
  taxes_sales: "Sales Tax (Tracked)", taxes_quarterly: "Estimated Quarterly Tax",
  charity_nonprofit: "Nonprofit Donations", charity_religious: "Religious Giving / Tithe",
  charity_fundraising: "Fundraising Contributions", charity_sponsorships: "Sponsorships",
  debt_credit_card: "Credit Card Payment", debt_personal_loan: "Personal Loan",
  debt_student_loan: "Student Loan", debt_medical: "Medical Debt",
  debt_bnpl: "Buy Now Pay Later (BNPL)", debt_collections: "Collections / Past Due",
  biz_office_supplies: "Office Supplies", biz_software_tools: "Software & Tools",
  biz_marketing: "Marketing & Advertising",
  biz_professional_services: "Professional Services", biz_travel: "Business Travel",
  biz_client_meals: "Client Meals & Entertainment", biz_equipment: "Equipment Purchase",
  other_exp_legal: "Legal Fees", other_exp_fines: "Fines & Penalties",
  other_exp_cash: "Cash Withdrawal", other_exp_misc: "Miscellaneous",
  // ─── Transfer — top level ──────────────────────────────────────────────────
  savings_investments: "Savings & Investments",
  account_transfers: "Account Transfers", pay_person: "Payments to People",
  // ─── Transfer — subcategories ──────────────────────────────────────────────
  savings_emergency_fund: "Emergency Fund", savings_hysa: "High-Yield Savings",
  savings_brokerage: "Brokerage Account", savings_crypto: "Cryptocurrency Purchase",
  savings_retirement: "Retirement Contribution (IRA/401k)",
  savings_cd: "CD / Money Market",
  transfer_checking_savings: "Checking to Savings",
  transfer_own_accounts: "Between Own Accounts",
  transfer_joint: "Joint Account Transfer", transfer_escrow: "Escrow / Trust Deposit",
  p2p_venmo_paypal_zelle: "Venmo / PayPal / Zelle", p2p_rent_roommate: "Rent to Roommate",
  p2p_split_bill: "Split Bill", p2p_loan_friend: "Loan to Friend",
  p2p_repayment: "Repayment Received",
};

export const TRANSFER_STATUS_LABELS: Record<string, string> = {
  initiated: "Initiated",
  pending: "Pending",
  processing: "Processing",
  posted: "Posted",
  failed: "Failed",
  reversed: "Reversed",
};

export const TRANSACTION_STATUS_LABELS: Record<string, string> = {
  pending: "Pending",
  posted: "Posted",
  failed: "Failed",
  cancelled: "Cancelled",
};
